# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'playfair.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 30, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.txt_Pl = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_Pl.setGeometry(QtCore.QRect(150, 100, 481, 71))
        self.txt_Pl.setObjectName("txt_Pl")
        self.txt_Cip = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_Cip.setGeometry(QtCore.QRect(150, 200, 481, 71))
        self.txt_Cip.setObjectName("txt_Cip")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 100, 51, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 210, 61, 16))
        self.label_3.setObjectName("label_3")
        self.btn_En = QtWidgets.QPushButton(self.centralwidget)
        self.btn_En.setGeometry(QtCore.QRect(140, 390, 75, 23))
        self.btn_En.setObjectName("btn_En")
        self.btn_De = QtWidgets.QPushButton(self.centralwidget)
        self.btn_De.setGeometry(QtCore.QRect(310, 390, 75, 23))
        self.btn_De.setObjectName("btn_De")
        self.btn_Ge = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Ge.setGeometry(QtCore.QRect(510, 390, 101, 23))
        self.btn_Ge.setObjectName("btn_Ge")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 300, 47, 13))
        self.label_4.setObjectName("label_4")
        self.txt_K = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_K.setGeometry(QtCore.QRect(150, 300, 481, 71))
        self.txt_K.setObjectName("txt_K")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 450, 141, 16))
        self.label_5.setObjectName("label_5")
        self.txt_Ge = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_Ge.setGeometry(QtCore.QRect(140, 440, 481, 71))
        self.txt_Ge.setObjectName("txt_Ge")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "PLAY FAIR"))
        self.label_2.setText(_translate("MainWindow", "PlainText"))
        self.label_3.setText(_translate("MainWindow", "Cipher Text"))
        self.btn_En.setText(_translate("MainWindow", "Encrypt"))
        self.btn_De.setText(_translate("MainWindow", "Decrypt"))
        self.btn_Ge.setText(_translate("MainWindow", "Generate Matrix"))
        self.label_4.setText(_translate("MainWindow", "Key"))
        self.label_5.setText(_translate("MainWindow", "Generate Matrix"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
